name: test

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Publish helm chart
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: testdata
